services:
  - type: web
    name: casegpt-api
    envVars:
      - key: GOOGLE_CREDS
        sync: false
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    region: frankfurt
